### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [bentiss/hid-replay#2]
Would you like to add more error handling for return values from functions like the following?
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html) ⇒ [find_hid_dbg](https://github.com/bentiss/hid-replay/blob/3f1c129eabb3f705d156c8c39ae3b14232572e8d/src/hid-recorder.c#L221)
- [signal](http://pubs.opengroup.org/onlinepubs/9699919799/functions/signal.html) ⇒ [main](https://github.com/bentiss/hid-replay/blob/78754c07ad452a02509cd9e2370eb14cd78241ea/src/hid-replay.c#L445)

**Comment by andy-shev** [comment]
Do you have real failures?

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?
