### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [bentiss/hid-replay#3]
The functions "[exit](http://pubs.opengroup.org/onlinepubs/9699919799/functions/exit.html)" and "[fclose](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fclose.html)" do not belong to the list of [async-signal-safe functions](https://www.securecoding.cert.org/confluence/display/c/SIG30-C.+Call+only+asynchronous-safe+functions+within+signal+handlers).
I guess that a different program design will be needed for your function "[signal_callback_handler](https://github.com/bentiss/hid-replay/blob/78754c07ad452a02509cd9e2370eb14cd78241ea/src/hid-replay.c#L436)".

**Comment by andy-shev** [comment]
I suppose `atexit()` should work well for the expected purpose.

**Comment by elfring** [comment]
Would you like to consider other software design options?
- [sigwaitinfo()](https://pubs.opengroup.org/onlinepubs/9699919799/functions/sigwaitinfo.html "Wait for queued signals.")
- [Self-pipe trick](http://cr.yp.to/docs/selfpipe.html)
