### ISSUE TITLE
No recent tags (Buildroot and other similar distos can't download anymore)

### ISSUE THREAD

**Issue by andy-shev** [bentiss/hid-replay#8]
Please, provide a tag for the **latest** versions.  Buildroot fails to download repository if I put `master` there.

**Comment by andy-shev** [comment]
Ping?
@whot?

**Comment by whot** [comment]
https://github.com/bentiss/hid-replay/releases seems to still have those listed? what am I missing here?

**Comment by andy-shev** [comment]
@whot look at the year (sic!) in the last commit there. (I added word **latest** in the initial report)

**Comment by whot** [comment]
I think #9 provides some context here :)

there hasn't been a release since and I suspect whatever is the next one will be the last anyway.

**Comment by andy-shev** [comment]
Indeed.

P.S. You may archive (make RO) of this one, btw.
